apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: harvester
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harvester
  targetCPUUtilizationPercentage: 80
